-- 테이블 생성 & 더비 데이터
-- 테이블 및 시퀀스 삭제 
DROP TABLE PERSON;
DROP TABLE JOB;
DROP SEQUENCE PSQ;
-- 테이블 및 시퀀스 생성
CREATE TABLE JOB (
    JNO   NUMBER(2) PRIMARY KEY,
    JNAME VARCHAR2(50) UNIQUE
);

CREATE TABLE PERSON (
    PNO NUMBER(5) PRIMARY KEY,
    PNAME VARCHAR2(50) NOT NULL,
    JNO NUMBER(2) NOT NULL,
    KOR NUMBER(3) CHECK(KOR>0),
    ENG NUMBER(3) CHECK(ENG>0),
    MAT NUMBER(3) CHECK(MAT>0),
    FOREIGN KEY (JNO) REFERENCES JOB(JNO)
);

CREATE SEQUENCE PSQ
    MAXVALUE 99999
    NOCACHE
    NOCYCLE;
-- 더미데이터 insert (정우성 ~ 송혜교)
INSERT INTO JOB VALUES (10, '배우'); 
INSERT INTO JOB VALUES (20, '가수');
INSERT INTO JOB VALUES (30, '엠씨');
SELECT * FROM JOB;

INSERT INTO PERSON VALUES (PSQ.NEXTVAL, '정우성', 10, 90, 80, 81); 
INSERT INTO PERSON VALUES (PSQ.NEXTVAL, '박세영', 10, 80, 90, 81); 
INSERT INTO PERSON VALUES (PSQ.NEXTVAL, '배수지', 20, 20, 90, 90); 
INSERT INTO PERSON VALUES (PSQ.NEXTVAL, '설수현', 20, 95, 95, 95); 
INSERT INTO PERSON VALUES (PSQ.NEXTVAL, '송혜교', 10, 100, 100, 100); 
SELECT * FROM PERSON;
commit;