-- drop
DROP TABLE AIRLINE;
DROP TABLE CITY;
DROP TABLE AIRPLANE;

-- create
CREATE TABLE CITY (
    CITYNAME VARCHAR2(100) NOT NULL PRIMARY KEY,
    CITYCODE VARCHAR2(10) NOT NULL
);

CREATE TABLE AIRPLANE (
    AIRNAME VARCHAR2(100) NOT NULL PRIMARY KEY,
    AIRSEAT NUMBER(3) NOT NULL
);

CREATE TABLE AIRLINE (
    ALID NUMBER(3) NOT NULL PRIMARY KEY,
    DCITY VARCHAR2(100) NOT NULL REFERENCES CITY(CITYNAME),
    ACITY VARCHAR2(100) NOT NULL REFERENCES CITY(CITYNAME),
    AIRNAME VARCHAR2(100) NOT NULL REFERENCES AIRPLANE(AIRNAME)
);

INSERT INTO CITY (CITYNAME, CITYCODE)
    VALUES ('서울 인천', 'ICN');
INSERT INTO CITY (CITYNAME, CITYCODE)
    VALUES ('서울 김포', 'GMP');
    
INSERT INTO AIRPLANE (AIRNAME, AIRSEAT)
    VALUES ('a-320', '100');
    
INSERT INTO AIRLINE (ALID, DCITY, ACITY, AIRNAME)
    VALUES ('1', '서울 인천', '서울 김포', 'a-320');
    


















