-- drop
DROP TABLE AIRLINE;
DROP TABLE CITY;
DROP TABLE PLANE;

-- 항공권 create
CREATE TABLE CITY (
    CTNAME VARCHAR2(100) NOT NULL PRIMARY KEY,
    CTCODE VARCHAR2(10) NOT NULL
);

CREATE TABLE PLANE (
    PLNAME VARCHAR2(100) NOT NULL PRIMARY KEY,
    PLSEAT NUMBER(3) NOT NULL
);

CREATE TABLE AIRLINE (
    ALID NUMBER(3) NOT NULL PRIMARY KEY,
    DCITY VARCHAR2(100) NOT NULL REFERENCES CITY(CTNAME),
    ACITY VARCHAR2(100) NOT NULL REFERENCES CITY(CTNAME),
    PLNAME VARCHAR2(100) NOT NULL REFERENCES PLANE(PLNAME)
);

INSERT INTO CITY (CTNAME, CTCODE)
    VALUES ('서울 인천', 'ICN');
INSERT INTO CITY (CTNAME, CTCODE)
    VALUES ('서울 김포', 'GMP');
INSERT INTO CITY (CTNAME, CTCODE)
    VALUES ('영국 런던', 'LON');
INSERT INTO CITY (CTNAME, CTCODE)
    VALUES ('한국 제주', 'CJU');
    
INSERT INTO PLANE (PLNAME, PLSEAT)
    VALUES ('a-320', '100');

--INSERT INTO AIRLINE (ALID, CITY, PLNAME)
 --   VALUES ('1', '서울 인천', 'a-320');
    
INSERT INTO AIRLINE (ALID, DCITY, ACITY, PLNAME)
    VALUES ('1', '서울 인천', '서울 김포', 'a-320');

    
SELECT * FROM AIRLINE A, PLANE P
    WHERE A.PLNAME = P.PLNAME;

SELECT * 
    FROM AIRLINE A, PLANE P , CITY C
    WHERE A.PLNAME = P.PLNAME AND A.DCITY = C.CTNAME OR A.ACITY = C.CTNAME;
    


















